apiVersion: apps/v1
kind: Deployment
metadata:
  name: xuanwu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xuanwu
  template:
    metadata:
      labels:
        app: xuanwu
    spec:
      containers:
        - name: xuanwu
          image: wolifexingo/xuanwu:v1.1
          ports:
            - containerPort: 3000
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: "mongodb://admin:admin-password@mongodb-service:27017"
            - name: SERVICE_NAME
              value: "xuanwu"
            - name: PPROF_PORT
              value: "3001"
            - name: UPTRACE_DSN
              value: "http://project2_secret_token@localhost:14317/2"
